# Generated by Django 5.2.5 on 2025-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('f_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
